module.exports = {
  AUTH: `/auth`,
  USER: `/user`,
  ADMIN: `/admin`,
  ROLE: `/role`,
  MODEL: `/model`,
  PROJECT: `/project`,
  BOOKING: `/booking`,
  TRANSACTION: `/transaction`,
  BOOK: `/book`,
  CATEGORY: `/category`,
  TAG: `/tag`,
  BLOG: `/blog`,
  MEETING: `/meeting`,
  SEARCH:'/search',
  SUBSCRIPTION:`/Subscribe`,
  SCHEDULE : '/schedule',
  EVENTS : '/event',
  CONTACT : '/contact',
  NOTIFICATION : '/notification',
  COMMISSION : '/commission',
};
